/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './index.html',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        blue: {
          DEFAULT: '#0F2C59',
          1: '#3C5377',
          2: '#77859C',
          3: '#A0AEC0',
          4: '#BFC9D9',
          5: '#ECEEF2',
          6: '#E2EBF6',
          7: '#F5F5FA',
          8: '#8083A3',
          9: '#278EFF',
          10: '#F6F7F9',
          11: '#D0D5DD',
          12: '#F3F6FF',
          13: '#D9DEE8',
          14: '#0063FF',
          15: '#D8E2EC',
          16: '#EAEAEC',
        },
        sky: {
          DEFAULT: '#3483FF',
          1: '#278EFF',
          2: '#DEFBFF',
          3: '#3059EA',
          4: '#0BACC2',
          5: '#0B93E2',
        },
        orange: {
          DEFAULT: '#FF3D00',
          1: '#DAC0A3',
          2: '#EADBC8',
          3: '#F8F0E5',
          4: '#FFECE5',
          5: '#C3A182',
          6: '#E7862E',
          7: '#FFF4F0',
          8: '#FFECE7',
          9: '#FBFBFF',
          10: '#FFDBCF',
          11: '#FFE1C6',
        },
        green: {
          DEFAULT: '#09BE06',
          1: '#E5FFE8',
          2: '#66CB9F',
          3: '#DEFFDE',
          4: '#CAFFC9',
        },
        purple: {
          DEFAULT: '#D730F2',
          1: '#FCE8FF',
          2: '#BA06BE',
        },
        yellow: {
          DEFAULT: '#D99E07',
          1: '#FFF3D6',
          2: '#E5A506',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      fontSize: {
        xss: '9px',
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        '4xl': '30px',
        '5xl': '32px',
        '6xl': '36px',
        '7xl': '40px',
        '8xl': '50px',
        '9xl': '60px',
      },
      fontFamily: {
        'public-sans': 'Public Sans',
      },
      lineHeight: {
        1: '1em',
        2: '8px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        4.5: '18px',
        5: '20px',
        5.5: '22px',
        6: '24px',
        6.5: '26px',
        7: '28px',
        7.5: '30px',
        8: '32px',
        8.5: '34px',
        9: '36px',
        10: '40px',
        12: '44px',
        14: '48px',
        14.5: '50px',
        15: '52px',
        16: '56px',
        17: '60px',
        18: '74px',
      },
      transitionDuration: {
        default: '150ms',
      },
      boxShadow: {
        box: '0px 3px 4px 0px #33333316',
        'box-sm': '1px 4px 15px 0px #8da8d11a',
        dropdown: '0px 0px 10px 2px #42546633',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {height: 0},
          to: {height: 'var(--radix-accordion-content-height)'},
        },
        'accordion-up': {
          from: {height: 'var(--radix-accordion-content-height)'},
          to: {height: 0},
        },
        'infinite-scroll': {
          from: {transform: 'translateX(0)'},
          to: {transform: 'translateX(-100%)'},
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'infinite-scroll': 'infinite-scroll 18s linear infinite',
      },
      padding: {
        '7px': '7px',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography'), require('tailwind-scrollbar-hide')],
}
