export {PersonalInfo} from './personal-info'
export {PassportInfo} from './passport-info'
export {Education} from './education'
export {LicencesCertifications} from './licences-certifications'
export {Achievements} from './achievements'
export {WorkExperience} from './work-experience'
export {Resume} from './resume'
export {Others} from './others'
