import {CAIcon, CNIcon, SEIcon, UKIcon, USIcon, UZIcon} from '@/icons/flags'

export const COUNTRIES = [
  {
    name: 'Canada',
    shortName: 'ca',
    code: '+1',
    flag: <CAIcon />,
  },
  {
    name: 'China',
    shortName: 'cn',
    code: '+86',
    flag: <CNIcon />,
  },
  {
    name: 'Sweden',
    shortName: 'se',
    code: '+46',
    flag: <SEIcon />,
  },
  {
    name: 'United Kingdom',
    shortName: 'uk',
    code: '+44',
    flag: <UKIcon />,
  },
  {
    name: 'United States',
    shortName: 'us',
    code: '+1',
    flag: <USIcon />,
  },
  {
    name: 'Uzbekistan',
    shortName: 'uz',
    code: '+998',
    flag: <UZIcon />,
  },
]

export const STATES = [
  {name: 'Alberta', country: 'Canada'},
  {name: 'British Columbia', country: 'Canada'},
  {name: 'Manitoba', country: 'Canada'},
  {name: 'New Brunswick', country: 'Canada'},
  {name: 'Newfoundland and Labrador', country: 'Canada'},
  {name: 'Nova Scotia', country: 'Canada'},
  {name: 'Ontario', country: 'Canada'},
  {name: 'Prince Edward Island', country: 'Canada'},
  {name: 'Quebec', country: 'Canada'},
  {name: 'Saskatchewan', country: 'Canada'},
  {name: 'Northwest Territories', country: 'Canada'},
  {name: 'Nunavut', country: 'Canada'},
  {name: 'Yukon', country: 'Canada'},
  {name: 'Beijing', country: 'China'},
  {name: 'Tianjin', country: 'China'},
  {name: 'Hebei', country: 'China'},
  {name: 'Shanxi', country: 'China'},
  {name: 'Inner Mongolia', country: 'China'},
  {name: 'Liaoning', country: 'China'},
  {name: 'Jilin', country: 'China'},
  {name: 'Heilongjiang', country: 'China'},
  {name: 'Shanghai', country: 'China'},
  {name: 'Jiangsu', country: 'China'},
  {name: 'Zhejiang', country: 'China'},
  {name: 'Anhui', country: 'China'},
  {name: 'Fujian', country: 'China'},
  {name: 'Jiangxi', country: 'China'},
  {name: 'Shandong', country: 'China'},
  {name: 'Henan', country: 'China'},
  {name: 'Hubei', country: 'China'},
  {name: 'Hunan', country: 'China'},
  {name: 'Guangdong', country: 'China'},
  {name: 'Guangxi', country: 'China'},
  {name: 'Hainan', country: 'China'},
  {name: 'Chongqing', country: 'China'},
  {name: 'Sichuan', country: 'China'},
  {name: 'Guizhou', country: 'China'},
  {name: 'Yunnan', country: 'China'},
  {name: 'Tibet', country: 'China'},
  {name: 'Shaanxi', country: 'China'},
  {name: 'Gansu', country: 'China'},
  {name: 'Qinghai', country: 'China'},
  {name: 'Ningxia', country: 'China'},
  {name: 'Xinjiang', country: 'China'},
  {name: 'Hong Kong', country: 'China'},
  {name: 'Macau', country: 'China'},
  {name: 'Blekinge County', country: 'Sweden'},
  {name: 'Dalarna County', country: 'Sweden'},
  {name: 'Gotland County', country: 'Sweden'},
  {name: 'Gävleborg County', country: 'Sweden'},
  {name: 'Halland County', country: 'Sweden'},
  {name: 'Jämtland County', country: 'Sweden'},
  {name: 'Jönköping County', country: 'Sweden'},
  {name: 'Kalmar County', country: 'Sweden'},
  {name: 'Kronoberg County', country: 'Sweden'},
  {name: 'Norrbotten County', country: 'Sweden'},
  {name: 'Örebro County', country: 'Sweden'},
  {name: 'Östergötland County', country: 'Sweden'},
  {name: 'Skåne County', country: 'Sweden'},
  {name: 'Södermanland County', country: 'Sweden'},
  {name: 'Stockholm County', country: 'Sweden'},
  {name: 'Uppsala County', country: 'Sweden'},
  {name: 'Värmland County', country: 'Sweden'},
  {name: 'Västerbotten County', country: 'Sweden'},
  {name: 'Västernorrland County', country: 'Sweden'},
  {name: 'Västmanland County', country: 'Sweden'},
  {name: 'Västra Götaland County', country: 'Sweden'},
  {name: 'East Midlands', country: 'United Kingdom'},
  {name: 'East of England', country: 'United Kingdom'},
  {name: 'London', country: 'United Kingdom'},
  {name: 'North East', country: 'United Kingdom'},
  {name: 'North West', country: 'United Kingdom'},
  {name: 'South East', country: 'United Kingdom'},
  {name: 'South West', country: 'United Kingdom'},
  {name: 'West Midlands', country: 'United Kingdom'},
  {name: 'Yorkshire and the Humber', country: 'United Kingdom'},
  {name: 'Aberdeen City', country: 'United Kingdom'},
  {name: 'Aberdeenshire', country: 'United Kingdom'},
  {name: 'Angus', country: 'United Kingdom'},
  {name: 'Argyll and Bute', country: 'United Kingdom'},
  {name: 'Clackmannanshire', country: 'United Kingdom'},
  {name: 'Dumfries and Galloway', country: 'United Kingdom'},
  {name: 'Dundee City', country: 'United Kingdom'},
  {name: 'East Ayrshire', country: 'United Kingdom'},
  {name: 'East Dunbartonshire', country: 'United Kingdom'},
  {name: 'East Lothian', country: 'United Kingdom'},
  {name: 'East Renfrewshire', country: 'United Kingdom'},
  {name: 'Edinburgh', country: 'United Kingdom'},
  {name: 'Eilean Siar', country: 'United Kingdom'},
  {name: 'Falkirk', country: 'United Kingdom'},
  {name: 'Fife', country: 'United Kingdom'},
  {name: 'Glasgow City', country: 'United Kingdom'},
  {name: 'Highland', country: 'United Kingdom'},
  {name: 'Inverclyde', country: 'United Kingdom'},
  {name: 'Midlothian', country: 'United Kingdom'},
  {name: 'Moray', country: 'United Kingdom'},
  {name: 'North Ayrshire', country: 'United Kingdom'},
  {name: 'North Lanarkshire', country: 'United Kingdom'},
  {name: 'Orkney Islands', country: 'United Kingdom'},
  {name: 'Perth and Kinross', country: 'United Kingdom'},
  {name: 'Renfrewshire', country: 'United Kingdom'},
  {name: 'Scottish Borders', country: 'United Kingdom'},
  {name: 'Shetland Islands', country: 'United Kingdom'},
  {name: 'South Ayrshire', country: 'United Kingdom'},
  {name: 'South Lanarkshire', country: 'United Kingdom'},
  {name: 'Stirling', country: 'United Kingdom'},
  {name: 'West Dunbartonshire', country: 'United Kingdom'},
  {name: 'West Lothian', country: 'United Kingdom'},
  {name: 'Blaenau Gwent', country: 'United Kingdom'},
  {name: 'Bridgend', country: 'United Kingdom'},
  {name: 'Caerphilly', country: 'United Kingdom'},
  {name: 'Cardiff', country: 'United Kingdom'},
  {name: 'Carmarthenshire', country: 'United Kingdom'},
  {name: 'Ceredigion', country: 'United Kingdom'},
  {name: 'Conwy', country: 'United Kingdom'},
  {name: 'Denbighshire', country: 'United Kingdom'},
  {name: 'Flintshire', country: 'United Kingdom'},
  {name: 'Gwynedd', country: 'United Kingdom'},
  {name: 'Isle of Anglesey', country: 'United Kingdom'},
  {name: 'Merthyr Tydfil', country: 'United Kingdom'},
  {name: 'Monmouthshire', country: 'United Kingdom'},
  {name: 'Neath Port Talbot', country: 'United Kingdom'},
  {name: 'Newport', country: 'United Kingdom'},
  {name: 'Pembrokeshire', country: 'United Kingdom'},
  {name: 'Powys', country: 'United Kingdom'},
  {name: 'Rhondda Cynon Taf', country: 'United Kingdom'},
  {name: 'Swansea', country: 'United Kingdom'},
  {name: 'Torfaen', country: 'United Kingdom'},
  {name: 'Vale of Glamorgan', country: 'United Kingdom'},
  {name: 'Wrexham', country: 'United Kingdom'},
  {name: 'Antrim and Newtownabbey', country: 'United Kingdom'},
  {name: 'Armagh City, Banbridge and Craigavon', country: 'United Kingdom'},
  {name: 'Belfast', country: 'United Kingdom'},
  {name: 'Causeway Coast and Glens', country: 'United Kingdom'},
  {name: 'Derry and Strabane', country: 'United Kingdom'},
  {name: 'Fermanagh and Omagh', country: 'United Kingdom'},
  {name: 'Lisburn and Castlereagh', country: 'United Kingdom'},
  {name: 'Mid and East Antrim', country: 'United Kingdom'},
  {name: 'Mid Ulster', country: 'United Kingdom'},
  {name: 'Newry, Mourne and Down', country: 'United Kingdom'},
  {name: 'Alabama', country: 'United States'},
  {name: 'Alaska', country: 'United States'},
  {name: 'Arizona', country: 'United States'},
  {name: 'Arkansas', country: 'United States'},
  {name: 'California', country: 'United States'},
  {name: 'Colorado', country: 'United States'},
  {name: 'Connecticut', country: 'United States'},
  {name: 'Delaware', country: 'United States'},
  {name: 'Florida', country: 'United States'},
  {name: 'Georgia', country: 'United States'},
  {name: 'Hawaii', country: 'United States'},
  {name: 'Idaho', country: 'United States'},
  {name: 'Illinois', country: 'United States'},
  {name: 'Indiana', country: 'United States'},
  {name: 'Iowa', country: 'United States'},
  {name: 'Kansas', country: 'United States'},
  {name: 'Kentucky', country: 'United States'},
  {name: 'Louisiana', country: 'United States'},
  {name: 'Maine', country: 'United States'},
  {name: 'Maryland', country: 'United States'},
  {name: 'Massachusetts', country: 'United States'},
  {name: 'Michigan', country: 'United States'},
  {name: 'Minnesota', country: 'United States'},
  {name: 'Mississippi', country: 'United States'},
  {name: 'Missouri', country: 'United States'},
  {name: 'Montana', country: 'United States'},
  {name: 'Nebraska', country: 'United States'},
  {name: 'Nevada', country: 'United States'},
  {name: 'New Hampshire', country: 'United States'},
  {name: 'New Jersey', country: 'United States'},
  {name: 'New Mexico', country: 'United States'},
  {name: 'New York', country: 'United States'},
  {name: 'North Carolina', country: 'United States'},
  {name: 'North Dakota', country: 'United States'},
  {name: 'Ohio', country: 'United States'},
  {name: 'Oklahoma', country: 'United States'},
  {name: 'Oregon', country: 'United States'},
  {name: 'Pennsylvania', country: 'United States'},
  {name: 'Rhode Island', country: 'United States'},
  {name: 'South Carolina', country: 'United States'},
  {name: 'South Dakota', country: 'United States'},
  {name: 'Tennessee', country: 'United States'},
  {name: 'Texas', country: 'United States'},
  {name: 'Utah', country: 'United States'},
  {name: 'Vermont', country: 'United States'},
  {name: 'Virginia', country: 'United States'},
  {name: 'Washington', country: 'United States'},
  {name: 'West Virginia', country: 'United States'},
  {name: 'Wisconsin', country: 'United States'},
  {name: 'Wyoming', country: 'United States'},
  {name: 'Andijan', country: 'Uzbekistan'},
  {name: 'Bukhara', country: 'Uzbekistan'},
  {name: 'Fergana', country: 'Uzbekistan'},
  {name: 'Jizzakh', country: 'Uzbekistan'},
  {name: 'Karakalpakstan', country: 'Uzbekistan'},
  {name: 'Namangan', country: 'Uzbekistan'},
  {name: 'Navoiy', country: 'Uzbekistan'},
  {name: 'Qashqadaryo', country: 'Uzbekistan'},
  {name: 'Samarqand', country: 'Uzbekistan'},
  {name: 'Sirdaryo', country: 'Uzbekistan'},
  {name: 'Surxondaryo', country: 'Uzbekistan'},
  {name: 'Tashkent City', country: 'Uzbekistan'},
  {name: 'Tashkent Region', country: 'Uzbekistan'},
  {name: 'Xorazm', country: 'Uzbekistan'},
]
