export {CAIcon} from './ca'
export {CNIcon} from './cn'
export {SEIcon} from './se'
export {UKIcon} from './uk'
export {USIcon} from './us'
export {UZIcon} from './uz'
export {RuIcon} from './ru'
export {KRIcon} from './kr'
